Repository cloudforet-io/plugin-google-cloud-iam-inven-collector, pull requests merged in 2024-07, with the labels that each got.

#39 Apply pagination to list_groups method
  src/plugin/connector/cloud_identity_connector.py
  src/plugin/manager/iam/group_manager.py
Labels: bug, pass/signedoff

#41 Change IAM role data name (data.type --> role.type)
  src/plugin/connector/cloud_identity_connector.py
  src/plugin/manager/iam/role_manager.py
  src/plugin/metadata/role.yaml
  src/plugin/metrics/IAM/Role/role_count.yaml
Labels: pass/signedoff, fail/signedoff

#42 Changed IAM Role, Group, and Permission data type names
  src/plugin/connector/logging_connector.py
  src/plugin/manager/iam/group_manager.py
  src/plugin/manager/iam/permission_manager.py
  src/plugin/manager/iam/role_manager.py
  src/plugin/manager/iam/service_account_manager.py
  src/plugin/metadata/group.yaml
  src/plugin/metadata/permission.yaml
  src/plugin/metadata/role.yaml
  src/plugin/metadata/service_account.yaml
  src/plugin/metrics/IAM/Group/group_member_count.yaml
  src/plugin/metrics/IAM/Permission/permission_count.yaml
  src/plugin/metrics/IAM/Permission/rb_count.yaml
  src/plugin/metrics/IAM/Role/role_count.yaml
Labels: fail/signedoff

#43 Changed the style of the policyAnalyzerEnabled field (boolean --> str/enum)
  src/plugin/manager/iam/service_account_manager.py
  src/plugin/metadata/service_account.yaml
Labels: pass/signedoff

#44 Added api_retry_handler to retry the google api call for 503 server errors
  src/plugin/connector/cloud_identity_connector.py
  src/plugin/manager/iam/group_manager.py
  src/plugin/utils/__init__.py
  src/plugin/utils/error_handlers.py
Labels: pass/signedoff

#45 Added caching mechanism for member lookup
  src/plugin/manager/iam/group_manager.py
Labels: pass/signedoff

#46 Changed caching mechanism for member lookup(now using member's id instead of membership name)
  src/plugin/manager/iam/group_manager.py
Labels: pass/signedoff

#47 Made 'Analyzer Enabled' field a default field in Service Account table
  src/plugin/metadata/service_account.yaml
Labels: pass/signedoff
